In [5]:
import numpy as np
forenheit=np.array([0,-10,-5,-15,0])
#formula for conversion from forenheit to celciu is ((F-32)*(5/9)=C)
celcius=(forenheit-32)*(5/9)
print(celcius)
print(celcius>-20)
print(celcius%2==0)


[-17.77777778 -23.33333333 -20.55555556 -26.11111111 -17.77777778]
[ True False False False  True]
[False False False False False]


In [7]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
c=a@b
print(c)

55


In [14]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
c=a*b                     #for element wise product we use '*' sign
d=a@b                     #for matrix product we can use '@' or 'np.dot()' function
print(d)         
print(np.dot(a,b))

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]


In [14]:
import numpy as np
import random
a=np.linspace(0,1,10)
print(a)
b=np.arange(10,50,2)
print(b)
c=np.random.rand(2,3)
print(c)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[[0.6757096  0.27777526 0.03132025]
 [0.22999597 0.79523325 0.40922589]]


In [15]:
numbers=[1,2,3,4,5]
squared_numbers=map(lambda x:x**2,numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [16]:
squared_numbers=[x**2 for x in numbers]
print(squared_numbers)

[1, 4, 9, 16, 25]
